services:
  # Repository interfaces
  App\Domain\User\Repository\UserRepositoryInterface:
    alias: App\Infrastructure\Repository\DoctrineUserRepository

  App\Domain\Product\Repository\ProductRepositoryInterface:
    alias: App\Infrastructure\Repository\DoctrineProductRepository

  App\Domain\Product\Repository\ProductCategoryRepositoryInterface:
    alias: App\Infrastructure\Repository\DoctrineProductCategoryRepository

  App\Domain\Pricing\Repository\ClientPriceRepositoryInterface:
    alias: App\Infrastructure\Repository\DoctrineClientPriceRepository

  App\Domain\Settings\Repository\SettingsRepositoryInterface:
    alias: App\Infrastructure\Repository\DoctrineSettingsRepository

  App\Domain\Lead\Repository\LeadRepositoryInterface:
    alias: App\Infrastructure\Repository\DoctrineLeadRepository

  # Repository implementations
  App\Infrastructure\Repository\DoctrineUserRepository:
    arguments:
      - '@doctrine.orm.entity_manager'

  App\Infrastructure\Repository\DoctrineProductRepository:
    arguments:
      - '@doctrine.orm.entity_manager'

  App\Infrastructure\Repository\DoctrineClientPriceRepository:
    arguments:
      - '@doctrine.orm.entity_manager'

  App\Infrastructure\Repository\DoctrineSettingsRepository:
    arguments:
      - '@doctrine'

  App\Infrastructure\Repository\DoctrineLeadRepository:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@knp_paginator'
