doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            User:
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/User/Model'
                prefix: 'App\Domain\User\Model'
                alias: User
            Product:
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Product/Model'
                prefix: 'App\Domain\Product\Model'
                alias: Product
            Pricing:
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Pricing/Model'
                prefix: 'App\Domain\Pricing\Model'
                alias: Pricing
            Cart:
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Cart/Model'
                prefix: 'App\Domain\Cart\Model'
                alias: Cart
            Order:
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Order/Model'
                prefix: 'App\Domain\Order\Model'
                alias: Order
            Settings:
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Settings/Model'
                prefix: 'App\Domain\Settings\Model'
                alias: Settings

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
