# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Import our hexagonal architecture service configurations
imports:
    - { resource: services/*.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    product_images_directory: '%kernel.project_dir%/public/uploads/products'
    pagination.products_per_page: 9
    pagination.new_order_products_per_page: 20
    # Email configuration
    email.from_email: '%env(MAIL_FROM_EMAIL)%'
    email.from_name: '%env(MAIL_FROM_NAME)%'
    email.admin_emails: '%env(csv:MAIL_ADMIN_EMAILS)%'
    email.notifications_enabled: '%env(bool:MAIL_NOTIFICATIONS_ENABLED)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/*/Model/'
            - '../src/Kernel.php'

    # Add repository interface tagging for specific repository interfaces
    _instanceof:
        App\Domain\Pricing\Repository\ClientPriceRepositoryInterface:
            tags: ['app.repository']
        App\Domain\Product\Repository\ProductRepositoryInterface:
            tags: ['app.repository']
        App\Domain\Product\Repository\ProductCategoryRepositoryInterface:
            tags: ['app.repository']
        App\Domain\User\Repository\UserRepositoryInterface:
            tags: ['app.repository']
        App\Domain\Settings\Repository\SettingsRepositoryInterface:
            tags: ['app.repository']

    # Service configurations for new services
    App\Application\Product\ProductImageService:
        arguments:
            $productImagesDirectory: '%product_images_directory%'
    
    App\Application\Product\ProductController:
        arguments:
            $productsPerPage: '%pagination.products_per_page%'
            $newOrderProductsPerPage: '%pagination.new_order_products_per_page%'

    # Email service configuration
    App\Application\Email\EmailService:
        arguments:
            $fromEmail: '%email.from_email%'
            $fromName: '%email.from_name%'
            $adminEmails: '%email.admin_emails%'

    # Email event listeners configuration
    App\Application\EventListener\OrderCreatedEmailListener:
        arguments:
            $emailNotificationsEnabled: '%email.notifications_enabled%'

    App\Application\EventListener\OrderStatusChangedEmailListener:
        arguments:
            $emailNotificationsEnabled: '%email.notifications_enabled%'

    App\Application\EventListener\OrderShippedEmailListener:
        arguments:
            $emailNotificationsEnabled: '%email.notifications_enabled%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
